Refactor branch validation

diff --git a/bin/script-functions b/bin/script-functions
--- a/bin/script-functions
+++ b/bin/script-functions
@@ -9,6 +9,21 @@ function contains {
 	return 1
 }
 
+function is-valid-branch {
+	if [ "$#" -ne "1" ]
+	then
+		echo "Invalid argument count (1) when calling is-valid-branch"
+		exit 1
+	fi
+
+	if git rev-parse --abbrev-ref ${1} &> /dev/null
+	then
+		return 0
+	else
+		return 1
+	fi
+}
+
 function save-branch {
 	if ! SCRIPT_FUNCTIONS_SAVED_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 	then
